// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  guideSidebar:
  // [
  //   {
  //     type: 'category',
  //     label: 'Guides',
  //     collapsible: true,
  //     collapsed: false,
  //     items: [
  //       'intro',
  //       {
  //         type: 'category',
  //         label: 'Git',
  //         items: [
  //           'git/README',
  //           'git/instalacion-configuracion',
  //           'git/conceptos-comandos-esenciales',
  //           'git/gitignore',
  //           { id: 'git/ramas', label: 'Ramas', type: 'doc'  }
  //         ],
  //       },
  //     ],
  //   },
  // ],

  [
    'intro',
    {
      type: 'category',
      label: 'Preparación',
      items: [
        'preparacion/conceptos-basicos',
        'preparacion/el-editor-de-texto',
        'preparacion/la-linea-de-comandos',
        'preparacion/git-y-github',
      ],
    },
    {
      type: 'category',
      label: 'Git',
      items: [
        'git/README',
        'git/instalacion-configuracion',
        'git/conceptos-comandos-esenciales',
        'git/gitignore',
        { id: 'git/ramas', label: 'Ramas', type: 'doc'  },
        'git/repositorios-remotos',
        { id: 'git/etiquetas', label: 'Etiquetas', type: 'doc'  },
        'git/reescribiendo-la-historia',
        { id: 'git/stashing', label: 'Stashing', type: 'doc'  },
        'git/github',
      ],
    },
    {
      type: 'category',
      label: 'HTML y CSS',
      items: [
        'html-y-css/README',
        'html-y-css/introduccion-a-html',
        'html-y-css/introduccion-a-css',
        'html-y-css/mas-elementos-de-html',
        'html-y-css/tablas',
        'html-y-css/formularios',
        'html-y-css/el-modelo-de-caja-en-css',
        'html-y-css/fondos-backgrounds',
        'html-y-css/posicionamiento',
        'html-y-css/selectores-css',
        'html-y-css/bordes-sombras-y-gradientes',
        'html-y-css/media-queries',
        'html-y-css/unidades',
        'html-y-css/flexbox',
      ],
    },
  ],
};

module.exports = sidebars;
